# Generated by Django 5.2 on 2025-04-28 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='verification_completed_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='verification_notes',
        ),
        migrations.RemoveField(
            model_name='user',
            name='verification_requested_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='verification_status',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='actif'),
        ),
    ]
