# Generated by Django 5.2 on 2025-04-28 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_verification_completed_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_completed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date de vérification complétée'),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_notes',
            field=models.TextField(blank=True, verbose_name='notes de vérification'),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_requested_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date de demande de vérification'),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_status',
            field=models.CharField(choices=[('unverified', 'Non vérifié'), ('pending', 'En attente'), ('verified', 'Vérifié'), ('rejected', 'Rejeté')], default='unverified', max_length=20, verbose_name='statut de vérification'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='actif'),
        ),
    ]
