# Generated by Django 5.2 on 2025-05-09 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_teacher_options_teacher_approval_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisor',
            name='expertise_areas',
            field=models.JSONField(blank=True, default=list, help_text='Domaines de spécialisation du conseiller', verbose_name="domaines d'expertise"),
        ),
    ]
