# Generated by Django 5.2 on 2025-06-17 20:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_advisor_expertise_areas'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='identity_document',
            field=models.FileField(blank=True, help_text="Document d'identité scanné (PDF ou image)", null=True, upload_to='teacher_identity/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpg', 'jpeg'])], verbose_name="document d'identité"),
        ),
    ]
