# Generated by Django 5.2 on 2025-06-18 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_teacher_identity_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advisor',
            name='expertise_areas',
        ),
    ]
