services:
  - type: web
    name: mon-projet-django
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn nom_du_projet.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: nom_du_projet.settings
      - key: SECRET_KEY
        value: votre_cle_secrete
      - key: DATABASE_URL
        fromDatabase:
          name: nom-base
          property: connectionString

