services:
  - type: web
    name: education_platform-django
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn education_platform.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: education_platform.settings
      - key: SECRET_KEY
        value: votre_cle_secrete
      - key: DATABASE_URL
        fromDatabase:
          name: nom-base
          property: connectionString

