# Generated by Django 5.2 on 2025-04-21 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='titre')),
                ('conversation_type', models.CharField(choices=[('direct', 'Message direct'), ('group', 'Groupe'), ('support', 'Support'), ('system', 'Système')], max_length=10, verbose_name='type de conversation')),
                ('is_group', models.BooleanField(default=False, verbose_name='est un groupe')),
                ('group_avatar', models.ImageField(blank=True, null=True, upload_to='conversation_avatars/', verbose_name='avatar du groupe')),
                ('group_description', models.TextField(blank=True, verbose_name='description du groupe')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('last_message_at', models.DateTimeField(auto_now_add=True, verbose_name='dernier message le')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='type de contenu')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_conversations', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
            ],
            options={
                'verbose_name': 'conversation',
                'verbose_name_plural': 'conversations',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('text', 'Texte'), ('image', 'Image'), ('file', 'Fichier'), ('audio', 'Audio'), ('video', 'Vidéo'), ('location', 'Localisation'), ('system', 'Système')], default='text', max_length=10, verbose_name='type de message')),
                ('content', models.TextField(blank=True, verbose_name='contenu')),
                ('image', models.ImageField(blank=True, null=True, upload_to='message_images/', verbose_name='image')),
                ('file', models.FileField(blank=True, null=True, upload_to='message_files/', verbose_name='fichier')),
                ('file_name', models.CharField(blank=True, max_length=255, verbose_name='nom du fichier')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='taille du fichier')),
                ('media_duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='durée du média')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='longitude')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('is_edited', models.BooleanField(default=False, verbose_name='est édité')),
                ('is_delivered', models.BooleanField(default=False, verbose_name='est délivré')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='délivré le')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.conversation', verbose_name='conversation')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='messaging.message', verbose_name='message parent')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='expéditeur')),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False, verbose_name='est administrateur')),
                ('is_muted', models.BooleanField(default=False, verbose_name='est muet')),
                ('notify_on_new_message', models.BooleanField(default=True, verbose_name='notifier sur nouveau message')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='rejoint le')),
                ('last_read_at', models.DateTimeField(auto_now_add=True, verbose_name='dernier lu le')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='messaging.conversation', verbose_name='conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'participant de conversation',
                'verbose_name_plural': 'participants de conversation',
                'unique_together': {('conversation', 'user')},
            },
        ),
        migrations.CreateModel(
            name='MessageReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(max_length=50, verbose_name='réaction')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='messaging.message', verbose_name='message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_reactions', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'réaction à un message',
                'verbose_name_plural': 'réactions aux messages',
                'unique_together': {('message', 'user')},
            },
        ),
        migrations.CreateModel(
            name='MessageRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True, verbose_name='lu le')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='messaging.message', verbose_name='message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_reads', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'lecture de message',
                'verbose_name_plural': 'lectures de messages',
                'unique_together': {('message', 'user')},
            },
        ),
    ]
