# Ce fichier permet l'importation depuis le dossier views
# Importation des vues mobiles pour maintenir la compatibilité avec le code existant

from .mobile import (
    AnalyticsDashboardView,
    ReportListView,
    ReportDetailView,
    ReportGenerateView,
    ReportDownloadView,
    MetricListView,
    MetricDetailView,
    UserActivityListView,
    UserStatsView,
    ResourceStatsView,
    AppointmentStatsView,
    OrientationStatsView,
    WidgetDataAPIView,
    MetricValueAPIView,
    StatsAPIView,
    TrackEventAPIView,
    UserActivityViewSet,
    ReportViewSet,
    MetricViewSet,
    AnalyticsEventViewSet,
)

from .web import (
    DashboardListView,
    DashboardDetailView,
    DashboardCreateView,
    DashboardUpdateView,
    DashboardDeleteView,
    WidgetCreateView,
    WidgetUpdateView,
    WidgetDeleteView,
    WidgetRefreshView,
    ReportCreateView,
    ReportUpdateView,
    DashboardViewSet,
    DashboardWidgetViewSet,
)

# Exporter toutes les vues pour l'API mobile et web
__all__ = [
    'AnalyticsDashboardView',
    'ReportListView',
    'ReportDetailView',
    'ReportGenerateView',
    'ReportDownloadView',
    'MetricListView',
    'MetricDetailView',
    'UserActivityListView',
    'UserStatsView',
    'ResourceStatsView',
    'AppointmentStatsView',
    'OrientationStatsView',
    'WidgetDataAPIView',
    'MetricValueAPIView',
    'StatsAPIView',
    'TrackEventAPIView',
    'UserActivityViewSet',
    'ReportViewSet',
    'MetricViewSet',
    'AnalyticsEventViewSet',
    'DashboardListView',
    'DashboardDetailView',
    'DashboardCreateView',
    'DashboardUpdateView',
    'DashboardDeleteView',
    'WidgetCreateView',
    'WidgetUpdateView',
    'WidgetDeleteView',
    'WidgetRefreshView',
    'ReportCreateView',
    'ReportUpdateView',
    'DashboardViewSet',
    'DashboardWidgetViewSet',
]