# Generated by Django 5.2 on 2025-04-21 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='code')),
                ('name', models.CharField(max_length=255, verbose_name='nom')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('title_template', models.CharField(max_length=255, verbose_name='modèle de titre')),
                ('body_template', models.TextField(verbose_name='modèle de corps')),
                ('has_email', models.BooleanField(default=True, verbose_name='envoi par email')),
                ('has_in_app', models.BooleanField(default=True, verbose_name="envoi dans l'application")),
                ('has_push', models.BooleanField(default=False, verbose_name='envoi par notification push')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='icône')),
                ('color', models.CharField(blank=True, max_length=20, verbose_name='couleur')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('default_user_preference', models.BooleanField(default=True, verbose_name='préférence utilisateur par défaut')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordre')),
            ],
            options={
                'verbose_name': 'type de notification',
                'verbose_name_plural': 'types de notification',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='code')),
                ('name', models.CharField(max_length=255, verbose_name='nom')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('subject_template', models.CharField(blank=True, max_length=255, verbose_name="modèle de sujet d'email")),
                ('email_template', models.TextField(blank=True, verbose_name="modèle d'email")),
                ('title_template', models.CharField(max_length=255, verbose_name='modèle de titre')),
                ('body_template', models.TextField(verbose_name='modèle de corps')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('notification_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='notifications.notificationtype', verbose_name='type de notification')),
            ],
            options={
                'verbose_name': 'modèle de notification',
                'verbose_name_plural': 'modèles de notification',
                'ordering': ['notification_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, verbose_name='token')),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web')], max_length=10, verbose_name='plateforme')),
                ('device_name', models.CharField(blank=True, max_length=255, verbose_name="nom de l'appareil")),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('last_used_at', models.DateTimeField(auto_now=True, verbose_name='dernière utilisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': "token d'appareil",
                'verbose_name_plural': "tokens d'appareil",
                'unique_together': {('user', 'token')},
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='titre')),
                ('body', models.TextField(verbose_name='corps')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('action_url', models.CharField(blank=True, max_length=255, verbose_name="URL d'action")),
                ('action_text', models.CharField(blank=True, max_length=100, verbose_name="texte d'action")),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='données')),
                ('status', models.CharField(choices=[('unread', 'Non lue'), ('read', 'Lue'), ('archived', 'Archivée')], default='unread', max_length=10, verbose_name='statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='lu le')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='archivé le')),
                ('sent_by_email', models.BooleanField(default=False, verbose_name='envoyé par email')),
                ('sent_by_push', models.BooleanField(default=False, verbose_name='envoyé par notification push')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='type de contenu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
                ('notification_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='notifications.notificationtype', verbose_name='type de notification')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='notificatio_user_id_7088ed_idx'), models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserNotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True, verbose_name='email activé')),
                ('in_app_enabled', models.BooleanField(default=True, verbose_name='notifications in-app activées')),
                ('push_enabled', models.BooleanField(default=True, verbose_name='notifications push activées')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('notification_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to='notifications.notificationtype', verbose_name='type de notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'préférence de notification',
                'verbose_name_plural': 'préférences de notification',
                'unique_together': {('user', 'notification_type')},
            },
        ),
    ]
